#!/usr/bin/python3
# -*- coding: utf-8 -*-

# GNOME Sudoku is a simple sudoku generator and player. Sudoku is a
# japanese logic puzzle.
#
# Copyright (c) 2005 Tom Hinkle You may use and distribute this
# software under the terms of the GNU General Public License, version
# 2 or later.

try:
    import bugbuddy
    bugbuddy.install('gnome-sudoku')
except:
    pass

try:
    # Import gnome-sudoku module from source distribution.
    from lib.gnome_sudoku import start_game
except ImportError:
    from gnome_sudoku.gnome_sudoku import start_game

start_game()
