#!/usr/bin/python
# Copyright (c) 2005 Tom Hinkle You may use and distribute this
# software under the terms of the GNU General Public License, version
# 2 or later

try:
    from gnome_sudoku.gnome_sudoku import start_game
except ImportError:
    import sys
    sys.path.append('/usr/share/gnome-sudoku/')
    from gnome_sudoku.gnome_sudoku import start_game

start_game()
